/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volunteer-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Volunteer Application */
        post: operations["create_volunteer_application_api_v1_volunteer_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-impact/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Donation Impact Options */
        get: operations["get_donation_impact_options_api_v1_donation_impact_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-impact/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Donation Impact */
        post: operations["preview_donation_impact_api_v1_donation_impact_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Donation Intent */
        post: operations["create_donation_intent_api_v1_donation_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Donor Profile */
        post: operations["create_donor_profile_api_v1_donor_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Donor Session */
        post: operations["create_donor_session_api_v1_donor_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Donor Session */
        delete: operations["delete_donor_session_api_v1_donor_sessions_current_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Donor Profile */
        get: operations["get_my_donor_profile_api_v1_donor_profiles_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-intents/{donation_intent_id}/wall-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Wall Post */
        post: operations["create_wall_post_api_v1_donation_intents__donation_intent_id__wall_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-wall/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Wall Posts */
        get: operations["get_my_wall_posts_api_v1_donor_wall_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings_api_v1_bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questionnaire-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Questionnaire Submission */
        post: operations["create_questionnaire_submission_api_v1_questionnaire_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Social Post */
        post: operations["create_social_post_api_v1_social_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_social_post_api_v1_social_posts_post */
        Body_create_social_post_api_v1_social_posts_post: {
            /** Platforms */
            platforms: string[];
            /**
             * Caption
             * @default
             */
            caption: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /** Caption Instagram */
            caption_instagram?: string | null;
            /** Caption Facebook */
            caption_facebook?: string | null;
        };
        /** BookingCreate */
        BookingCreate: {
            /** Member Slug */
            member_slug: string;
            /** Event Id */
            event_id: string;
            /** Event Date */
            event_date: string;
        };
        /** BookingResponse */
        BookingResponse: {
            /** Id */
            id: string;
            /** Member Slug */
            member_slug: string;
            /** Event Id */
            event_id: string;
            /** Event Date */
            event_date: string;
            /**
             * Status
             * @constant
             */
            status: "confirmed";
            /** Booked At */
            booked_at: string;
        };
        /**
         * CauseId
         * @enum {string}
         */
        CauseId: "where_needed_most" | "dance" | "sports" | "nutrition" | "family_support";
        /** ContributionImpact */
        ContributionImpact: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /** Copy Key */
            copy_key: string;
            /**
             * Is Estimate
             * @default true
             * @constant
             */
            is_estimate: true;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "contribution";
            /** Estimated Units */
            estimated_units?: null;
            /** Unit Key */
            unit_key: string;
        };
        /** CountedImpact */
        CountedImpact: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /** Copy Key */
            copy_key: string;
            /**
             * Is Estimate
             * @default true
             * @constant
             */
            is_estimate: true;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "counted";
            /** Estimated Units */
            estimated_units: number;
            /** Unit Key */
            unit_key: string;
        };
        /** DonationCauseOption */
        DonationCauseOption: {
            cause_id: components["schemas"]["CauseId"];
            /** Copy Key */
            copy_key: string;
        };
        /** DonationImpactOptionsResponse */
        DonationImpactOptionsResponse: {
            default_cause_id: components["schemas"]["CauseId"];
            /** Preset Amounts Hkd */
            preset_amounts_hkd: number[];
            /** Causes */
            causes: components["schemas"]["DonationCauseOption"][];
            /**
             * Demo Estimates
             * @default true
             * @constant
             */
            demo_estimates: true;
        };
        /** DonationIntentRequest */
        DonationIntentRequest: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /**
             * Anonymous
             * @default false
             */
            anonymous: boolean;
        };
        /** DonationIntentResponse */
        DonationIntentResponse: {
            /** Donation Intent Id */
            donation_intent_id: string;
            /**
             * Status
             * @constant
             */
            status: "simulated";
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Persistence
             * @default stored
             * @constant
             */
            persistence: "stored";
            /** Impact */
            impact: components["schemas"]["CountedImpact"] | components["schemas"]["ContributionImpact"] | components["schemas"]["FlexibleImpact"];
        };
        /** DonorAuthResponse */
        DonorAuthResponse: {
            profile: components["schemas"]["DonorSummary"];
        };
        /** DonorDonation */
        DonorDonation: {
            /** Donation Intent Id */
            donation_intent_id: string;
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /**
             * Currency
             * @constant
             */
            currency: "HKD";
            /**
             * Status
             * @default simulated
             * @constant
             */
            status: "simulated";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Impact */
            impact: components["schemas"]["CountedImpact"] | components["schemas"]["ContributionImpact"] | components["schemas"]["FlexibleImpact"];
        };
        /** DonorProfileCreate */
        DonorProfileCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Nickname */
            nickname: string;
            /** Name */
            name?: string | null;
            /**
             * Consent To Updates
             * @default false
             */
            consent_to_updates: boolean;
        };
        /** DonorProfileResponse */
        DonorProfileResponse: {
            profile: components["schemas"]["DonorSummary"];
            /** Lifetime Amount Hkd */
            lifetime_amount_hkd: number;
            /** Donation Count */
            donation_count: number;
            /** Donations */
            donations: components["schemas"]["DonorDonation"][];
        };
        /** DonorSessionCreate */
        DonorSessionCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** DonorSummary */
        DonorSummary: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Nickname */
            nickname: string;
            /** Name */
            name: string;
            /** Consent To Updates */
            consent_to_updates: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FlexibleImpact */
        FlexibleImpact: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /** Copy Key */
            copy_key: string;
            /**
             * Is Estimate
             * @default true
             * @constant
             */
            is_estimate: true;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "flexible";
            /** Estimated Units */
            estimated_units?: null;
            /** Unit Key */
            unit_key?: null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
        };
        /**
         * HelpPath
         * @enum {string}
         */
        HelpPath: "child" | "adult" | "family" | "other";
        /** ImpactPreviewRequest */
        ImpactPreviewRequest: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
        };
        /**
         * PlatformResult
         * @description Outcome for a single platform. Platforms are published independently,
         *     so one can succeed while another fails.
         */
        PlatformResult: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "instagram" | "facebook";
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "failed";
            /**
             * Caption
             * @description The caption actually used for this platform.
             */
            caption?: string | null;
            /** Permalink */
            permalink?: string | null;
            /** Media Url */
            media_url?: string | null;
            /**
             * Error
             * @description Meta's own error message when status is 'failed'.
             */
            error?: string | null;
        };
        /** QuestionnaireRequest */
        QuestionnaireRequest: {
            path: components["schemas"]["HelpPath"];
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Message */
            message?: string | null;
            /**
             * Consent
             * @default false
             */
            consent: boolean;
        };
        /** QuestionnaireResponse */
        QuestionnaireResponse: {
            /** Reference */
            reference: string;
            /**
             * Status
             * @constant
             */
            status: "submitted";
            /** Suggested Path */
            suggested_path: string;
            /**
             * Persistence
             * @default stored
             * @constant
             */
            persistence: "stored";
        };
        /** SocialPostResponse */
        SocialPostResponse: {
            /** Image Urls */
            image_urls?: string[];
            /** Results */
            results: components["schemas"]["PlatformResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolunteerApplicationRequest */
        VolunteerApplicationRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role_id: components["schemas"]["VolunteerRoleId"];
            session_id?: components["schemas"]["VolunteerSessionId"] | null;
            first_step: components["schemas"]["VolunteerFirstStep"];
            /** Consent */
            consent: boolean;
        };
        /** VolunteerApplicationResponse */
        VolunteerApplicationResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Persistence
             * @default none
             * @constant
             */
            persistence: "none";
            /**
             * Status
             * @enum {string}
             */
            status: "interest_submitted" | "pending_confirmation";
            role_id: components["schemas"]["VolunteerRoleId"];
            session_id: components["schemas"]["VolunteerSessionId"] | null;
            /** Next Steps */
            next_steps: string[];
        };
        /**
         * VolunteerFirstStep
         * @enum {string}
         */
        VolunteerFirstStep: "observe" | "trial" | "interest_only";
        /**
         * VolunteerRoleId
         * @enum {string}
         */
        VolunteerRoleId: "dance_activity_buddy" | "sports_activity_buddy" | "community_event_volunteer" | "nutrition_class_assistant" | "family_support_assistant" | "sports_class_leader" | "enrichment_class_leader";
        /**
         * VolunteerSessionId
         * @enum {string}
         */
        VolunteerSessionId: "saturday_dance_project" | "sunday_sports_session" | "dragon_boat_training_day" | "nutrition_cooking_workshop" | "family_support_afternoon" | "community_csr_volunteer_day";
        /** WallPostCreate */
        WallPostCreate: {
            /** Message */
            message?: string | null;
        };
        /** WallPostResponse */
        WallPostResponse: {
            /** Id */
            id: string;
            /** Donation Intent Id */
            donation_intent_id: string;
            /** Nickname */
            nickname: string;
            /** Message */
            message: string | null;
            /**
             * Status
             * @constant
             */
            status: "pending";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_volunteer_application_api_v1_volunteer_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolunteerApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolunteerApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_donation_impact_options_api_v1_donation_impact_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationImpactOptionsResponse"];
                };
            };
        };
    };
    preview_donation_impact_api_v1_donation_impact_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpactPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountedImpact"] | components["schemas"]["ContributionImpact"] | components["schemas"]["FlexibleImpact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_donation_intent_api_v1_donation_intents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                love21_donor_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DonationIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_donor_profile_api_v1_donor_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DonorProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorAuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_donor_session_api_v1_donor_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DonorSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorAuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_donor_session_api_v1_donor_sessions_current_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                love21_donor_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_donor_profile_api_v1_donor_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                love21_donor_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_wall_post_api_v1_donation_intents__donation_intent_id__wall_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                donation_intent_id: string;
            };
            cookie?: {
                love21_donor_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WallPostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WallPostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_wall_posts_api_v1_donor_wall_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                love21_donor_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WallPostResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_v1_bookings_get: {
        parameters: {
            query?: {
                member_slug?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_questionnaire_submission_api_v1_questionnaire_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionnaireRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionnaireResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_social_post_api_v1_social_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_social_post_api_v1_social_posts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialPostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
