/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volunteer-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Volunteer Application */
        post: operations["create_volunteer_application_api_v1_volunteer_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Donation Intent */
        post: operations["create_donation_intent_api_v1_donation_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings_api_v1_bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookingCreate */
        BookingCreate: {
            /** Member Slug */
            member_slug: string;
            /** Event Id */
            event_id: string;
            /** Event Date */
            event_date: string;
        };
        /** BookingResponse */
        BookingResponse: {
            /** Id */
            id: string;
            /** Member Slug */
            member_slug: string;
            /** Event Id */
            event_id: string;
            /** Event Date */
            event_date: string;
            /**
             * Status
             * @constant
             */
            status: "confirmed";
            /** Booked At */
            booked_at: string;
        };
        /** DonationIntentRequest */
        DonationIntentRequest: {
            /** Amount */
            amount: number;
            /**
             * Currency
             * @default HKD
             * @constant
             */
            currency: "HKD";
            program: components["schemas"]["DonationProgram"];
            /**
             * Anonymous
             * @default false
             */
            anonymous: boolean;
            /** Donor Name */
            donor_name?: string | null;
            /** Email */
            email?: string | null;
        };
        /** DonationIntentResponse */
        DonationIntentResponse: {
            /** Reference */
            reference: string;
            /**
             * Status
             * @constant
             */
            status: "simulated";
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /** Impact Message */
            impact_message: string;
            /** Acknowledgement */
            acknowledgement: string;
            /**
             * Persistence
             * @default stored
             * @constant
             */
            persistence: "stored";
        };
        /**
         * DonationProgram
         * @enum {string}
         */
        DonationProgram: "general" | "sports" | "nutrition" | "enrichment" | "family_support" | "community";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolunteerApplicationRequest */
        VolunteerApplicationRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Interests */
            interests: components["schemas"]["VolunteerInterest"][];
            availability: components["schemas"]["VolunteerAvailability"];
            /** Message */
            message?: string | null;
            /** Consent */
            consent: boolean;
        };
        /** VolunteerApplicationResponse */
        VolunteerApplicationResponse: {
            /** Reference */
            reference: string;
            /**
             * Status
             * @constant
             */
            status: "submitted";
            /** Next Steps */
            next_steps: string[];
            /**
             * Persistence
             * @default none
             * @constant
             */
            persistence: "none";
        };
        /**
         * VolunteerAvailability
         * @enum {string}
         */
        VolunteerAvailability: "weekday" | "evening" | "weekend" | "flexible";
        /**
         * VolunteerInterest
         * @enum {string}
         */
        VolunteerInterest: "sports" | "community" | "family_support" | "nutrition" | "enrichment";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_volunteer_application_api_v1_volunteer_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolunteerApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolunteerApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_donation_intent_api_v1_donation_intents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DonationIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_v1_bookings_get: {
        parameters: {
            query?: {
                member_slug?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
