/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volunteer-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Volunteer Application */
        post: operations["create_volunteer_application_api_v1_volunteer_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-impact/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Donation Impact Options */
        get: operations["get_donation_impact_options_api_v1_donation_impact_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-impact/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Donation Impact */
        post: operations["preview_donation_impact_api_v1_donation_impact_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donation-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Donation Intent */
        post: operations["create_donation_intent_api_v1_donation_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings_api_v1_bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookingCreate */
        BookingCreate: {
            /** Member Slug */
            member_slug: string;
            /** Event Id */
            event_id: string;
            /** Event Date */
            event_date: string;
        };
        /** BookingResponse */
        BookingResponse: {
            /** Id */
            id: string;
            /** Member Slug */
            member_slug: string;
            /** Event Id */
            event_id: string;
            /** Event Date */
            event_date: string;
            /**
             * Status
             * @constant
             */
            status: "confirmed";
            /** Booked At */
            booked_at: string;
        };
        /**
         * CauseId
         * @enum {string}
         */
        CauseId: "where_needed_most" | "dance" | "sports" | "nutrition" | "family_support";
        /** ContributionImpact */
        ContributionImpact: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /** Copy Key */
            copy_key: string;
            /**
             * Is Estimate
             * @default true
             * @constant
             */
            is_estimate: true;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "contribution";
            /** Estimated Units */
            estimated_units?: null;
            /** Unit Key */
            unit_key: string;
        };
        /** CountedImpact */
        CountedImpact: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /** Copy Key */
            copy_key: string;
            /**
             * Is Estimate
             * @default true
             * @constant
             */
            is_estimate: true;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "counted";
            /** Estimated Units */
            estimated_units: number;
            /** Unit Key */
            unit_key: string;
        };
        /** DonationCauseOption */
        DonationCauseOption: {
            cause_id: components["schemas"]["CauseId"];
            /** Copy Key */
            copy_key: string;
        };
        /** DonationImpactOptionsResponse */
        DonationImpactOptionsResponse: {
            default_cause_id: components["schemas"]["CauseId"];
            /** Preset Amounts Hkd */
            preset_amounts_hkd: number[];
            /** Causes */
            causes: components["schemas"]["DonationCauseOption"][];
            /**
             * Demo Estimates
             * @default true
             * @constant
             */
            demo_estimates: true;
        };
        /** DonationIntentRequest */
        DonationIntentRequest: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /**
             * Anonymous
             * @default false
             */
            anonymous: boolean;
            /** Donor Name */
            donor_name?: string | null;
            /** Donor Email */
            donor_email?: string | null;
            /**
             * Consent To Updates
             * @default false
             */
            consent_to_updates: boolean;
        };
        /** DonationIntentResponse */
        DonationIntentResponse: {
            /** Donation Intent Id */
            donation_intent_id: string;
            /**
             * Status
             * @constant
             */
            status: "simulated";
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Persistence
             * @default stored
             * @constant
             */
            persistence: "stored";
            /** Impact */
            impact: components["schemas"]["CountedImpact"] | components["schemas"]["ContributionImpact"] | components["schemas"]["FlexibleImpact"];
        };
        /** FlexibleImpact */
        FlexibleImpact: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
            /** Copy Key */
            copy_key: string;
            /**
             * Is Estimate
             * @default true
             * @constant
             */
            is_estimate: true;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "flexible";
            /** Estimated Units */
            estimated_units?: null;
            /** Unit Key */
            unit_key?: null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
        };
        /** ImpactPreviewRequest */
        ImpactPreviewRequest: {
            cause_id: components["schemas"]["CauseId"];
            /** Amount Hkd */
            amount_hkd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolunteerApplicationRequest */
        VolunteerApplicationRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role_id: components["schemas"]["VolunteerRoleId"];
            session_id?: components["schemas"]["VolunteerSessionId"] | null;
            first_step: components["schemas"]["VolunteerFirstStep"];
            /** Consent */
            consent: boolean;
        };
        /** VolunteerApplicationResponse */
        VolunteerApplicationResponse: {
            /**
             * Simulation
             * @default true
             * @constant
             */
            simulation: true;
            /**
             * Persistence
             * @default none
             * @constant
             */
            persistence: "none";
            /**
             * Status
             * @enum {string}
             */
            status: "interest_submitted" | "pending_confirmation";
            role_id: components["schemas"]["VolunteerRoleId"];
            session_id: components["schemas"]["VolunteerSessionId"] | null;
            /** Next Steps */
            next_steps: string[];
        };
        /**
         * VolunteerFirstStep
         * @enum {string}
         */
        VolunteerFirstStep: "observe" | "trial" | "interest_only";
        /**
         * VolunteerRoleId
         * @enum {string}
         */
        VolunteerRoleId: "dance_activity_buddy" | "sports_activity_buddy" | "community_event_volunteer" | "nutrition_class_assistant" | "family_support_assistant" | "sports_class_leader" | "enrichment_class_leader";
        /**
         * VolunteerSessionId
         * @enum {string}
         */
        VolunteerSessionId: "saturday_dance_project" | "sunday_sports_session" | "dragon_boat_training_day" | "nutrition_cooking_workshop" | "family_support_afternoon" | "community_csr_volunteer_day";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_volunteer_application_api_v1_volunteer_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolunteerApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolunteerApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_donation_impact_options_api_v1_donation_impact_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationImpactOptionsResponse"];
                };
            };
        };
    };
    preview_donation_impact_api_v1_donation_impact_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpactPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountedImpact"] | components["schemas"]["ContributionImpact"] | components["schemas"]["FlexibleImpact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_donation_intent_api_v1_donation_intents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DonationIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonationIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_v1_bookings_get: {
        parameters: {
            query?: {
                member_slug?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
