import type { BookableEvent, FamilyAccount } from "./types";

export const bookableEvents: BookableEvent[] = [
  {
    id: "bev-1",
    title: "Saturday Sports: Bocce & Boxing",
    program: "sports",
    date: "9 Aug 2025",
    time: "10:00 – 12:00",
    spots: 4,
    location: "Love 21 Sports Hall",
    ageRange: "8–18",
    accent: "red",
  },
  {
    id: "bev-2",
    title: "Creative Arts Afternoon",
    program: "enrichment",
    date: "10 Aug 2025",
    time: "14:00 – 16:00",
    spots: 6,
    location: "Love 21 Art Studio",
    ageRange: "6–14",
    accent: "yellow",
  },
  {
    id: "bev-3",
    title: "Nutrition Workshop: Healthy Snacks",
    program: "nutrition",
    date: "11 Aug 2025",
    time: "11:00 – 13:00",
    spots: 5,
    location: "Love 21 Kitchen",
    ageRange: "10–18",
    accent: "orange",
  },
  {
    id: "bev-4",
    title: "Community Performance Rehearsal",
    program: "community",
    date: "12 Aug 2025",
    time: "14:00 – 16:00",
    spots: 8,
    location: "Community Hall",
    ageRange: "All ages",
    accent: "blue",
  },
  {
    id: "bev-5",
    title: "Family Support Circle",
    program: "family_support",
    date: "14 Aug 2025",
    time: "10:00 – 11:30",
    spots: 10,
    location: "Love 21 Family Room",
    ageRange: "Parents & carers",
    accent: "teal",
  },
  {
    id: "bev-6",
    title: "Dragon Boat Training",
    program: "sports",
    date: "16 Aug 2025",
    time: "08:00 – 11:00",
    spots: 12,
    location: "Stanley Beach",
    ageRange: "14+",
    accent: "red",
  },
  {
    id: "bev-7",
    title: "Music & Movement",
    program: "enrichment",
    date: "18 Aug 2025",
    time: "10:00 – 11:30",
    spots: 8,
    location: "Love 21 Studio",
    ageRange: "5–12",
    accent: "yellow",
  },
  {
    id: "bev-8",
    title: "Saturday Sports: Yoga & Balance",
    program: "sports",
    date: "23 Aug 2025",
    time: "10:00 – 11:30",
    spots: 6,
    location: "Love 21 Sports Hall",
    ageRange: "8–18",
    accent: "red",
  },
];

export const demoFamilies: FamilyAccount[] = [
  { id: "fam-1", name: "Sarah's family", memberSlugs: ["crystal", "ka-wai"] },
  { id: "fam-2", name: "Mr. Chan's family", memberSlugs: ["mei-ling"] },
];
